export default {
  AUTHENTICATION_REQUEST: "authentication/AUTHENTICATION_REQUEST",
  AUTHENTICATION_SUCCESS: "authentication/AUTHENTICATION_SUCCESS",
  AUTHENTICATION_LOGOUT: "authentication/AUTHENTICATION_LOGOUT",
} as const;
